### ISSUE TITLE
fall detection fails

### ISSUE THREAD

**Issue by RickChou** [limengdu/Seeed-Studio-MR60FDA1-Sersor#1]
I bought MR60FDA1 60GHz mmWave Sensor, I can detect human body successfully, but the example of fall detection fails, how to set or install it?

**Comment by limengdu** [comment]
To ensure the accuracy of radar detection, please install it on top!
The radar should be installed vertically with a horizontal deviation angle of ≤5° to ensure that the radar main beam covers the detection area; the radar installation height is recommended to be 2m≤H≤3m. No obvious obstructions and coverings in front of the radar. Affected by the radar installation height and radar beam range, the maximum radius of moving human detection in this installation mode is R3 ≈ 3 meters; the maximum radius of stationary human detection is R2 ≈ 2.25 meters; the radius of fall detection is R1 ≤ 2 meters.
