### ISSUE TITLE
E (151) gpio: esp_ipc_call_blocking failed (0x103)

### ISSUE THREAD

**Issue by roberbike** [limengdu/Seeed-Studio-MR60FDA1-Sersor#3]
I have this issue:
01:36:40.884 > rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
01:36:40.884 > configsip: 0, SPIWP:0xee
01:36:40.884 > clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
01:36:40.892 > mode:DIO, clock div:2    
01:36:40.900 > load:0x3fff0030,len:1184 
01:36:40.900 > load:0x40078000,len:13104
01:36:40.902 > load:0x40080400,len:3036 
01:36:40.902 > entry 0x400805e4
01:36:41.030 > E (151) gpio: esp_ipc_call_blocking failed (0x103)
01:36:41.034 > [     3][E][esp32-hal�,���c:175] __attachInterruptFunctionalArg(): GPIO ISR Service Failed To Start
01:36:41.058 > Ready

Platformio.ini:
[common]
platform = espressif32
framework = arduino
upload_speed = 921600
monitor_speed = 115200
version = 0.1.5
revision = 5
target = Devel
monitor_filters = time
extra_scripts = pre:prebuild.py
build_flags = 
	-D CORE_DEBUG_LEVEL=2
lib_deps = 
		https://github.com/limengdu/Seeed-Studio-MR60FDA1-Sersor.git
	jdollar/SoftwareSerialEsp32@0.0.0-alpha+sha.6d373ecd5f

[env:TTGOLORA32V1]
board = ttgo-lora32-v1
extends = common
build_flags = 
	${common.build_flags}
	-D RX_Pin=23
	-D TX_Pin=17

And in main.cpp your fallen example, adapting software serial.

With previous version of your library, it worked  ok.
Have I  something wrong?.
Thanks

**Comment by limengdu** [comment]
Hi, we do not support this board ttgo-lora32-v1, we currently support Arduino boards and XIAO series.
